# Urpo Configuration File
# Copy this to ~/.config/urpo/config.yaml or specify with --config flag
# All settings have sensible defaults, only override what you need

# Server configuration
server:
  # GRPC port for OTEL receiver (default: 4317)
  grpc_port: 4317

  # HTTP port for OTEL receiver (default: 4318)
  http_port: 4318

  # Bind address for receivers (default: 0.0.0.0 - all interfaces)
  bind_address: "0.0.0.0"

  # Maximum concurrent connections (default: 1000)
  max_connections: 1000

  # Connection timeout (default: 30s)
  connection_timeout: 30s

# Storage configuration
storage:
  # Maximum number of spans to store (default: 100000)
  max_spans: 100000

  # Maximum memory usage in MB (default: 1024)
  max_memory_mb: 1024

  # Span retention duration (default: 1h)
  retention_duration: 1h

  # Cleanup interval (default: 30s)
  cleanup_interval: 30s

  # Enable compression (default: false)
  compression_enabled: false

  # Enable persistent storage to disk (default: false)
  persistent: false

  # Data directory for persistent storage (default: ./urpo_data)
  data_dir: ./urpo_data

  # Hot storage size - in-memory ring buffer (default: 10000)
  hot_storage_size: 10000

  # Warm storage size in MB - memory-mapped files (default: 512)
  warm_storage_mb: 512

  # Cold storage retention in hours (default: 24)
  cold_retention_hours: 24

  # Enable archival storage for compressed historical data (default: false)
  enable_archival: false

# UI configuration
ui:
  # UI refresh rate (default: 100ms)
  refresh_rate: 100ms

  # Color theme: dark, light, auto (default: dark)
  theme: dark

  # Enable vim keybindings (default: true)
  vim_mode: true

  # Show help on startup (default: true)
  show_help: true

  # Default view: services, traces, spans (default: services)
  default_view: services

# Sampling configuration
sampling:
  # Default sampling rate, 0.0-1.0 (default: 1.0 - sample everything)
  default_rate: 1.0

  # Per-service sampling rates
  per_service:
    high-volume-service: 0.1    # Sample 10% of spans
    critical-service: 1.0        # Sample 100% of spans

  # Adaptive sampling enabled (default: false)
  adaptive: false

  # Target spans per second for adaptive sampling (optional)
  target_sps: 10000

# Monitoring configuration
monitoring:
  # Health check interval (default: 10s)
  health_check_interval: 10s

  # Metrics enabled (default: true)
  metrics_enabled: true

  # Metrics port (optional, default: none)
  # metrics_port: 9090

  # Alert thresholds
  alerts:
    # Error rate threshold percentage (default: 5.0)
    error_rate_threshold: 5.0

    # P95 latency threshold (default: 1s)
    p95_latency_threshold: 1s

    # Minimum sample size for alerts (default: 100)
    min_sample_size: 100

# Logging configuration
logging:
  # Log level: trace, debug, info, warn, error (default: info)
  level: info

  # Log file path (optional, default: none - stdout only)
  # file: /var/log/urpo/urpo.log

  # Log rotation: daily, hourly, size, never (default: daily)
  rotation: daily

  # Structured logging format (default: false)
  structured: false

# Feature configuration
features:
  # Enable experimental features (default: false)
  experimental: false

  # Enable performance profiling (default: false)
  profiling: false
