# Urpo Configuration Example
# Copy this to ~/.config/urpo/config.yaml and customize

# Server configuration
server:
  grpc_port: 4317
  http_port: 4318
  bind_address: "0.0.0.0"
  max_connections: 1000
  connection_timeout: 30s

# Storage configuration
storage:
  max_spans: 100000
  max_memory_mb: 1024
  retention_duration: 1h
  cleanup_interval: 30s
  compression_enabled: false

# UI configuration
ui:
  refresh_rate: 100ms
  theme: dark  # dark, light, auto
  vim_mode: true
  show_help: true
  default_view: services  # services, traces, spans

# Sampling configuration
sampling:
  default_rate: 1.0  # Sample 100% by default
  per_service:
    # Reduce sampling for high-volume services
    "payment-service": 0.1
    "user-service": 0.5
  adaptive: false
  # target_sps: 1000  # Target spans per second when adaptive is enabled

# Monitoring configuration
monitoring:
  health_check_interval: 10s
  metrics_enabled: true
  # metrics_port: 9090  # Prometheus metrics endpoint
  alerts:
    error_rate_threshold: 5.0  # Alert when error rate exceeds 5%
    p95_latency_threshold: 1s  # Alert when P95 exceeds 1 second
    min_sample_size: 100

# Logging configuration
logging:
  level: info  # trace, debug, info, warn, error
  # file: /var/log/urpo/urpo.log
  rotation: daily  # daily, hourly, size, never
  structured: false

# Feature flags
features:
  enable_fake_spans: true  # Generate demo data
  experimental: false
  profiling: false