# Rustfmt configuration for Urpo
# Optimized for readability and performance-focused code
# Using only stable features

# Basic formatting
edition = "2021"
hard_tabs = false
tab_spaces = 4
max_width = 100
use_small_heuristics = "Default"

# Imports (stable features only)
reorder_imports = true
reorder_modules = true

# Code organization
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

# Chain formatting for readable builder patterns
chain_width = 60
single_line_if_else_max_width = 50

# Function formatting
fn_params_layout = "Tall"
fn_call_width = 80

# Keep arrays readable for performance tuning
array_width = 80

# Match formatting
match_block_trailing_comma = true