[package]
name = "test_receiver"
version = "0.1.0"
edition = "2021"

[dependencies]
urpo_lib = { path = ".." }
tokio = { version = "1.40", features = ["rt-multi-thread", "macros", "signal", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }